// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vwatch
{
    internal sealed partial class Vsix
    {
        public const string Id = "vwatch.ab4ce8bc-e458-4d53-b679-e9f76a54d909";
        public const string Name = "VWatch";
        public const string Description = @"A Visual Studio extension that monitors a selected process and automatically attaches the debugger. VWatch can be configured to monitor multiple target processes for managed and native debugging sessions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "David James";
        public const string Tags = "";
    }
}
