// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vwatch
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string vwatchString = "54dc519c-c83f-48fa-8520-d6ae19513772";
        public static Guid vwatch = new Guid(vwatchString);

        public const string GuidVwatchImagesString = "ad951d5e-70ca-4db5-b3ba-272da224b1d1";
        public static Guid GuidVwatchImages = new Guid(GuidVwatchImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VWatchMenuGroup = 0x0001;
        public const int ShowConfigurationWindow = 0x0100;
        public const int vwatchIcon = 0x0001;
    }
}